### ISSUE TITLE
error in feature/msmarco_psg

### ISSUE THREAD

**Issue by Tooba-ts1700550** [capreolus-ir/capreolus#150] opened 2021-04-07 10:25 UTC
I am getting the following error when trying to use msmarcopsg, in benchmarks/msmarco.py at line 60:
IndexError: list index out of range

**Comment by andrewyates** [comment] 2021-04-07 10:41
This branch hasn't been merged yet, but maybe @crystina-z may be able to help.

**Comment by crystina-z** [comment] 2021-05-08 01:28
sorry for missing this. If the issue is still valid, @Tooba-ts1700550 could you provide the command and the link to the line that throws the error?

**Closed** 2021-06-07 13:44 UTC
